# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "configs",
    srcs = [
        "dhcpcd.conf",
        "group",
        "hostname",
        "network_setup.sh",
        "passwd",
        "pci_hw.cfg",
        "pci_server.cfg",
        "profile",
        "qcrypto.conf",
        "ssh_host_rsa_key",
        "ssh_host_rsa_key.pub",
        "sshd_config",
        "startup.sh",
    ],
    visibility = ["//tests:__subpackages__"],
)
