exports_files(
    ["lifecycle_demo.json"],
    visibility = ["//examples:__subpackages__"],
)

filegroup(
    name = "lifecycle_demo_config",
    srcs = ["lifecycle_demo.json"],
    visibility = ["//examples:__subpackages__"],
)
