' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml
title Control Interface Static Architecture

package "Launch Manager" {
    [Launch Manager (LM)] as LM
    interface ControlInterface
    
    LM -- ControlInterface : implements
}

package "State Manager" {
    [State Manager] as SM
}

SM -up-> ControlInterface : uses

note right of [ControlInterface] : Start/Stop/Restart components\nQuery status\n...

@enduml
