' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include hm_tag.puml
!include hm_error.puml
!include hm_status.puml
!include hm_duration_range.puml
!includesub hm_deadline.puml!DeadlineClass

!startsub DeadlineMonitorClass
+class DeadlineMonitor {
    +get_deadline(&self, tag: Tag) -> Result<Deadline, Error>
    +get_deadline_guard(&self, tag: Tag) -> Result<DeadlineGuard, Error>
    +create_custom_deadline(&self, duration_range: TimeRange) -> Result<Deadline, Error>
    +create_custom_deadline_guard(&self, duration_range: TimeRange) -> Result<DeadlineGuard, Error>
    +enable(&self) -> Result<(), Error>
    +disable(&self) -> Result<(), Error>
    ~status(&self) -> Status
    ~evaluate(&self) -> Status
}
!endsub

+class DeadlineGuard {
}

!startsub DeadlineMonitorRel
DeadlineMonitor *-- Status : owns
DeadlineMonitor ..> Error
DeadlineMonitor ..> Tag
DeadlineMonitor ..> Deadline : <<creates>>
DeadlineMonitor ..> DeadlineGuard : <<creates>>
DeadlineMonitor ..> TimeRange
!endsub

@enduml
