' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include lm_state.puml
!include hm_error.puml
!includesub lm_interface.puml!LogicMonitorClass

!startsub LogicMonitorBuilderClass
+class LogicMonitorBuilder {
    +new(initial_state: LogicMonitorState) -> Self
    +add_transition(&mut self, from: LogicMonitorState, to: LogicMonitorState) -> &mut Self
    +build(self) -> Result<LogicMonitor, Error>
}
!endsub

!startsub LogicMonitorBuilderRel
LogicMonitorBuilder ..> Error
LogicMonitorBuilder *-- "1..*" LogicMonitorState : owns
LogicMonitorBuilder ..> LogicMonitor : <<consumes>>
!endsub

@enduml