---
title: Ready State of a Non Reporting
---
sequenceDiagram
    participant lm as Launch Manager
    participant nr as Non Reporting

    activate lm
    lm->>nr:
    activate nr
    Note left of lm: Assume the non reporting process is in ready state
