# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

package(default_visibility = ["//visibility:public"])

alias(
    name = "health_monitoring_cc",
    actual = "//src/health_monitoring_lib:health_monitoring_lib_cc",
)

alias(
    name = "health_monitoring_rust",
    actual = "//src/health_monitoring_lib:health_monitoring_lib",
)
