' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml lm_reporting_running
title "Ready State of a Reporting Component"
participant "Launch Manager" as lm
participant "Reporting\nReady State: Running" as rs
activate lm
lm -> rs
activate rs
rs -> lm: "kRunning"
activate lm
note left of lm
    Reporting process has achieved ready state
end note
rs -> lm: Termination
deactivate lm
destroy rs

@enduml